# basic options
title: Non-Singularity
author:
  name: Purveyor-of-Ideas...
  email: atmagyaananubhavam@gmail.com

# Build settings
markdown: kramdown
remote_theme: jekyll/minima-reboot
#show_excerpts: true # set to true to show excerpts on the homepage
#excerpt_separator: <!--more-->
